import type { Metadata } from 'next'
import './globals.css'
import TopHeader from '@/components/topHeader'
import Header from '@/components/Header'
import "slick-carousel/slick/slick.css";
import Footer from '@/components/footer/Footer'
import Uparrow from '@/components/Uparrow'
import Layout from '@/components/Layout'



export const metadata: Metadata = {
  title: 'Flash – MultiPurpose WordPress Theme',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`w-full`}>
        <Layout>
      <TopHeader/>
      <Header/>
        {children}
        <Uparrow/>
        <Footer/>
        </Layout>
        </body>
    </html>
  )
}
